name: address_book
description: Address Book.

version: 1.0.3+3

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  sqflite: ^2.2.8+4
  lottie: ^2.4.0
  go_router: ^9.0.0
  flutter_native_splash: ^2.3.1
  path: ^1.8.3
  auto_injector: ^1.0.3
  result_dart: ^1.0.6
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon_1024.png"
  remove_alpha_ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/splash_screen_gradient.png
    - assets/logos/ava_logo_x80.png
    - assets/logos/full_logo.png
    - assets/logos/logo.png
    - assets/lotties/logo_lottie.json
    - assets/icons/map_mark_icon.png
    - assets/icons/app_icon_1024.png
    - 'assets/lotties/warning_lottie.json'
